class HullStats {

    constructor() {
        this.hulls = this.generateHulls();
    }

    getBaseHullStats(hull) {
        return this.hulls[hull];
    }

    generateHulls() {
        return {
            "light_freighter": {
                name: "light_freighter",
                display_name: "Terran Light Freighter",
                description: "The light freighter is primarily used by merchants for hauling goods but can be repurposed",
                base_value: 10000,
                base_initiative: 4,
                speed: 2,
                turning: 1,
                max_turrets: 1,
                scan_range: 2,
                front_armor: 20,
                right_armor: 20,
                left_armor: 20,
                rear_armor: 20,
                front_shield: 50,
                right_shield: 50,
                left_shield: 50,
                rear_shield: 50,
                core_health: 80,
                max_core_stress: 70,
                core_stress_threshold: 50,
                core_cooling: 15,
                shield_generator: 1,
                storage_space: 50,
                hard_points: [
                    {
                        id: 0,
                        name: "Top Turret",
                        size: 1,
                        fields_of_fire: [0, 1, 2, 3, 4, 5, 6, 7],
                        turret: null,
                    },
                ]
            }, 
            "light_scout": {
                name: "light_scout",
                display_name: "Terran Dart Scout Corvette",
                description: "Fast but lightly armed and armored, the light scout corevett is used for patrol and reconasaince",
                base_value: 25000,
                base_initiative: 2,
                speed: 4,
                turning: 2,
                max_turrets: 2,
                scan_range: 6,
                front_armor: 60,
                right_armor: 60,
                left_armor: 60,
                rear_armor: 50,
                front_shield: 80,
                right_shield: 80,
                left_shield: 80,
                rear_shield: 80,
                core_health: 100,
                max_core_stress: 100,
                core_stress_threshold: 60,
                core_cooling: 20,
                shield_generator: 1,
                storage_space: 5,
                hard_points: [
                    {
                        id: 0,
                        name: "Top Turret",
                        size: 1,
                        fields_of_fire: [0, 1, 2, 6, 7],
                        turret: null,
                    },
                    {
                        id: 1,
                        name: "Bottom Turret",
                        size: 1,
                        fields_of_fire: [0, 1, 2, 6, 7],
                        turret: null,
                    }
                ]
            },
            "wedge_destroyer": {
                name: "wedge_destroyer",
                display_name: "Terran Arrowhead Destroyer",
                description: "The Wedge packs immense firepower for its size. All turrets overlap fields of fire in the forward arc",
                base_value: 50000,
                base_initiative: 3,
                speed: 2,
                turning: 2,
                max_turrets: 5,
                scan_range: 3,
                front_armor: 300,
                right_armor: 290,
                left_armor: 290,
                rear_armor: 200,
                front_shield: 200,
                right_shield: 180,
                left_shield: 180,
                rear_shield: 100,
                core_health: 280,
                max_core_stress: 150,
                core_stress_threshold: 110,
                core_cooling: 50,
                shield_generator: 3,
                storage_space: 10,
                hard_points: [
                    {
                        id: 0,
                        name: "Nose Turret",
                        size: 1,
                        fields_of_fire: [0],
                        turret: null,
                    },
                    {
                        id: 1,
                        name: "Left Front Turret",
                        size: 2,
                        fields_of_fire: [0, 7],
                        turret: null,
                    },
                    {
                        id: 2,
                        name: "Right Front Turret",
                        size: 2,
                        fields_of_fire: [0, 1],
                        turret: null,
                    },
                    {
                        id: 3,
                        name: "Left Mid Turret",
                        size: 1,
                        fields_of_fire: [0, 7],
                        turret: null,
                    },
                    {
                        id: 4,
                        name: "Right Mid Turret",
                        size: 1,
                        fields_of_fire: [0, 1],
                        turret: null,
                    },
                ]
            },
            "medium_freighter": {
                name: "medium_freighter",
                display_name: "Medium Wallet Freighter",
                description: "Medium freighters form the backbone of most merchant fleets for their good cost to size ratio",
                base_value: 25000,
                base_initiative: 4,
                speed: 2,
                turning: 1,
                max_turrets: 5,
                scan_range: 2,
                front_armor: 50,
                right_armor: 50,
                left_armor: 50,
                rear_armor: 40,
                front_shield: 180,
                right_shield: 200,
                left_shield: 200,
                rear_shield: 180,
                core_health: 100,
                max_core_stress: 100,
                core_stress_threshold: 80,
                core_cooling: 20,
                shield_generator: 4,
                storage_space: 100,
                hard_points: [
                    {
                        id: 0,
                        name: "Top Turret",
                        size: 1,
                        fields_of_fire: [0, 1, 2, 3, 4, 5, 6, 7],
                        turret: null,
                    },
                    {
                        id: 1,
                        name: "Left Front Turret",
                        size: 1,
                        fields_of_fire: [6, 7],
                        turret: null,
                    },
                    {
                        id: 2,
                        name: "Right Front Turret",
                        size: 1,
                        fields_of_fire: [1, 2],
                        turret: null,
                    },
                    {
                        id: 3,
                        name: "Left Rear Turret",
                        size: 1,
                        fields_of_fire: [5, 6],
                        turret: null,
                    },
                    {
                        id: 4,
                        name: "Right Rear Turret",
                        size: 1,
                        fields_of_fire: [3, 4],
                        turret: null,
                    },
                ]
            },
            "shield_cruiser": {
                name: "shield_cruiser",
                display_name: "Dwarven Shield Cruiser",
                description: "Dwarven Shield style cruisers form a core part of their battle line, know for their exceptionally strong front armor, but not their maneuverability",
                base_value: 75000,
                base_initiative: 3,
                speed: 2,
                turning: 1,
                max_turrets: 6,
                scan_range: 3,
                front_armor: 440,
                right_armor: 360,
                left_armor: 360,
                rear_armor: 300,
                front_shield: 440,
                right_shield: 440,
                left_shield: 440,
                rear_shield: 300,
                core_health: 450,
                max_core_stress: 300,
                core_stress_threshold: 200,
                core_cooling: 100,
                shield_generator: 6,
                storage_space: 50,
                hard_points: [
                    {
                        id: 0,
                        name: "Left Turret",
                        size: 2,
                        fields_of_fire: [0, 6, 7],
                        turret: null,
                    },
                    {
                        id: 1,
                        name: "Left Front Turret",
                        size: 2,
                        fields_of_fire: [0, 7],
                        turret: null,
                    },
                    {
                        id: 2,
                        name: "Right Front Turret",
                        size: 2,
                        fields_of_fire: [0, 1],
                        turret: null,
                    },
                    {
                        id: 3,
                        name: "Right Turret",
                        size: 2,
                        fields_of_fire: [0, 1, 2],
                        turret: null,
                    },
                    {
                        id: 4,
                        name: "Left Rear Turret",
                        size: 1,
                        fields_of_fire: [4],
                        turret: null,
                    },
                    {
                        id: 5,
                        name: "Right Rear Turret",
                        size: 1,
                        fields_of_fire: [4],
                        turret: null,
                    },
                ]
            },
        }
    }

}