class HullStats {

    constructor() {
        this.hulls = this.generateHulls();
    }

    getBaseHullStats(hull) {
        return this.hulls[hull];
    }

    generateHulls() {
        return {
            "light_freighter": {
                name: "light_freighter",
                display_name: "Terran Light Freighter",
                description: "The light freighter is primarily used by merchants for hauling goods but can be repurposed",
                base_value: 10000,
                base_initiative: 4,
                speed: 2,
                turning: 1,
                max_turrets: 1,
                scan_range: 2,
                front_armor: 20,
                right_armor: 20,
                left_armor: 20,
                rear_armor: 20,
                front_shield: 50,
                right_shield: 50,
                left_shield: 50,
                rear_shield: 50,
                core_health: 40,
                max_core_stress: 100,
                core_stress_threshold: 70,
                core_cooling: 15,
                shield_generator: 1,
                storage_space: 50,
                hard_points: [
                    {
                        id: 0,
                        name: "Top Turret",
                        size: 1,
                        fields_of_fire: [0, 1, 2, 3, 4, 5, 6, 7],
                        turret: null,
                        active: true,
                    },
                ]
            }, 
            "light_scout": {
                name: "light_scout",
                display_name: "Terran Dart Scout Corvette",
                description: "Fast but lightly armed and armored, the light scout corevett is used for patrol and reconasaince",
                base_value: 10000,
                base_initiative: 2,
                speed: 4,
                turning: 2,
                max_turrets: 2,
                scan_range: 6,
                front_armor: 50,
                right_armor: 50,
                left_armor: 50,
                rear_armor: 45,
                front_shield: 50,
                right_shield: 50,
                left_shield: 50,
                rear_shield: 50,
                core_health: 55,
                max_core_stress: 200,
                core_stress_threshold: 180,
                core_cooling: 20,
                shield_generator: 1,
                storage_space: 5,
                hard_points: [
                    {
                        id: 0,
                        name: "Top Turret",
                        size: 1,
                        fields_of_fire: [0, 1, 2, 6, 7],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 1,
                        name: "Bottom Turret",
                        size: 1,
                        fields_of_fire: [0, 1, 2, 6, 7],
                        turret: null,
                        active: true,
                    }
                ]
            },
            "wedge_destroyer": {
                name: "wedge_destroyer",
                display_name: "Terran Arrowhead Destroyer",
                description: "The Wedge packs immense firepower for its size. All turrets overlap fields of fire in the forward arc",
                base_value: 18000,
                base_initiative: 3,
                speed: 2,
                turning: 2,
                max_turrets: 5,
                scan_range: 3,
                front_armor: 125,
                right_armor: 115,
                left_armor: 115,
                rear_armor: 100,
                front_shield: 125,
                right_shield: 115,
                left_shield: 115,
                rear_shield: 100,
                core_health: 120,
                max_core_stress: 800,
                core_stress_threshold: 700,
                core_cooling: 60,
                shield_generator: 3,
                storage_space: 10,
                hard_points: [
                    {
                        id: 0,
                        name: "Nose Turret",
                        size: 1,
                        fields_of_fire: [0],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 1,
                        name: "Left Front Turret",
                        size: 2,
                        fields_of_fire: [0, 7],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 2,
                        name: "Right Front Turret",
                        size: 2,
                        fields_of_fire: [0, 1],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 3,
                        name: "Left Mid Turret",
                        size: 1,
                        fields_of_fire: [0, 7],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 4,
                        name: "Right Mid Turret",
                        size: 1,
                        fields_of_fire: [0, 1],
                        turret: null,
                        active: true,
                    },
                ]
            },
            "medium_freighter": {
                name: "medium_freighter",
                display_name: "Medium Wallet Freighter",
                description: "Medium freighters form the backbone of most merchant fleets for their good cost to size ratio",
                base_value: 15000,
                base_initiative: 4,
                speed: 2,
                turning: 1,
                max_turrets: 5,
                scan_range: 2,
                front_armor: 60,
                right_armor: 60,
                left_armor: 60,
                rear_armor: 45,
                front_shield: 110,
                right_shield: 110,
                left_shield: 110,
                rear_shield: 110,
                core_health: 100,
                max_core_stress: 600,
                core_stress_threshold: 500,
                core_cooling: 20,
                shield_generator: 4,
                storage_space: 100,
                hard_points: [
                    {
                        id: 0,
                        name: "Top Turret",
                        size: 1,
                        fields_of_fire: [0, 1, 2, 3, 4, 5, 6, 7],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 1,
                        name: "Left Front Turret",
                        size: 1,
                        fields_of_fire: [6, 7],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 2,
                        name: "Right Front Turret",
                        size: 1,
                        fields_of_fire: [1, 2],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 3,
                        name: "Left Rear Turret",
                        size: 1,
                        fields_of_fire: [5, 6],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 4,
                        name: "Right Rear Turret",
                        size: 1,
                        fields_of_fire: [3, 4],
                        turret: null,
                        active: true,
                    },
                ]
            },
            "shield_cruiser": {
                name: "shield_cruiser",
                display_name: "Dwarven Shield Cruiser",
                description: "Dwarven Shield style cruisers form a core part of their battle line, know for their exceptionally strong front armor, but not their maneuverability",
                base_value: 23500,
                base_initiative: 3,
                speed: 2,
                turning: 1,
                max_turrets: 6,
                scan_range: 3,
                front_armor: 180,
                right_armor: 150,
                left_armor: 150,
                rear_armor: 135,
                front_shield: 220,
                right_shield: 200,
                left_shield: 200,
                rear_shield: 185,
                core_health: 180,
                max_core_stress: 1540,
                core_stress_threshold: 1350,
                core_cooling: 120,
                shield_generator: 6,
                storage_space: 50,
                hard_points: [
                    {
                        id: 0,
                        name: "Left Turret",
                        size: 2,
                        fields_of_fire: [0, 6, 7],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 1,
                        name: "Left Front Turret",
                        size: 2,
                        fields_of_fire: [0, 7],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 2,
                        name: "Right Front Turret",
                        size: 2,
                        fields_of_fire: [0, 1],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 3,
                        name: "Right Turret",
                        size: 2,
                        fields_of_fire: [0, 1, 2],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 4,
                        name: "Left Rear Turret",
                        size: 1,
                        fields_of_fire: [4],
                        turret: null,
                        active: true,
                    },
                    {
                        id: 5,
                        name: "Right Rear Turret",
                        size: 1,
                        fields_of_fire: [4],
                        turret: null,
                        active: true,
                    },
                ]
            },
        }
    }

}